# ASSUMPTIONS:
# - Underlying cluster should have 100+ nodes.
# - Number of nodes should be divisible by NODES_PER_NAMESPACE (default 100).

#Constants
{{$BIG_GROUP_SIZE := 250}}
{{$MEDIUM_GROUP_SIZE := 30}}
{{$SMALL_GROUP_SIZE := 5}}
{{$NODES_PER_NAMESPACE := 100}}
{{$PODS_PER_NODE := 30}}
{{$TEST_THROUGHPUT := 10}}
# bigRCs - 1/4 of all pods should be in big RCs.
{{$BIG_RCS_PER_NAMESPACE := 3}}
# mediumRCs - 1/4 of all pods should be in medium RCs.
{{$MEDIUM_RCS_PER_NAMESPACE := 25}}
# smallRCs - 1/2 of all pods should be in small RCs.
{{$SMALL_RCS_PER_NAMESPACE := 300}}

#Variables
{{$namespaces := DivideInt .Nodes $NODES_PER_NAMESPACE}}
{{$totalPods := MultiplyInt $namespaces $NODES_PER_NAMESPACE $PODS_PER_NODE}}
{{$saturationTime := DivideInt $totalPods $TEST_THROUGHPUT}}


name: load
automanagedNamespaces: {{$namespaces}}
tuningSets:
- name: RandomizedSaturationTimeLimited
  RandomizedTimeLimitedLoad:
    timeLimit: {{$saturationTime}}s
- name: RandomizedScalingTimeLimited
  RandomizedTimeLimitedLoad:
    # The expected number of created/deleted pods is totalPods/4 when scaling,
    # as each RC changes its size from X to a uniform random value in [X/2, 3X/2].
    # To match 10 [pods/s] requirement, we need to divide saturationTime by 4.
    timeLimit: {{DivideInt $saturationTime 4}}s
steps:
- measurements:
  - Identifier: APIResponsiveness
    Method: APIResponsiveness
    Params:
      action: reset
# Create RCs
- measurements:
  - Identifier: WaitForRunningRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      kind: ReplicationController
      labelSelector: group = load
      operationTimeout: 10m
- phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$BIG_RCS_PER_NAMESPACE}}
    tuningSet: RandomizedSaturationTimeLimited
    objectBundle:
    - basename: big-service
      objectTemplatePath: service.yaml
      templateFillMap:
        RCBasename: big-rc
    - basename: big-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        ReplicasMin: {{$BIG_GROUP_SIZE}}
        ReplicasMax: {{$BIG_GROUP_SIZE}}
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$MEDIUM_RCS_PER_NAMESPACE}}
    tuningSet: RandomizedSaturationTimeLimited
    objectBundle:
    - basename: medium-service
      objectTemplatePath: service.yaml
      templateFillMap:
        RCBasename: medium-rc
    - basename: medium-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        ReplicasMin: {{$MEDIUM_GROUP_SIZE}}
        ReplicasMax: {{$MEDIUM_GROUP_SIZE}}
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$SMALL_RCS_PER_NAMESPACE}}
    tuningSet: RandomizedSaturationTimeLimited
    objectBundle:
    - basename: small-service
      objectTemplatePath: service.yaml
      templateFillMap:
        RCBasename: small-rc
    - basename: small-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        ReplicasMin: {{$SMALL_GROUP_SIZE}}
        ReplicasMax: {{$SMALL_GROUP_SIZE}}
- measurements:
  - Identifier: WaitForRunningRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- name: Creating RCs
# Scale RCs
- phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$BIG_RCS_PER_NAMESPACE}}
    tuningSet: RandomizedScalingTimeLimited
    objectBundle:
    - basename: big-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        ReplicasMin: {{MultiplyInt $BIG_GROUP_SIZE 0.5}}
        ReplicasMax: {{MultiplyInt $BIG_GROUP_SIZE 1.5}}
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$MEDIUM_RCS_PER_NAMESPACE}}
    tuningSet: RandomizedScalingTimeLimited
    objectBundle:
    - basename: medium-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        ReplicasMin: {{MultiplyInt $MEDIUM_GROUP_SIZE 0.5}}
        ReplicasMax: {{MultiplyInt $MEDIUM_GROUP_SIZE 1.5}}
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$SMALL_RCS_PER_NAMESPACE}}
    tuningSet: RandomizedScalingTimeLimited
    objectBundle:
    - basename: small-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        ReplicasMin: {{MultiplyInt $SMALL_GROUP_SIZE 0.5}}
        ReplicasMax: {{MultiplyInt $SMALL_GROUP_SIZE 1.5}}
- measurements:
  - Identifier: WaitForRunningRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- name: Scaling RCs
# Delete RCs
- phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: RandomizedSaturationTimeLimited
    objectBundle:
    - basename: big-service
      objectTemplatePath: service.yaml
    - basename: big-rc
      objectTemplatePath: rc.yaml
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: RandomizedSaturationTimeLimited
    objectBundle:
    - basename: medium-service
      objectTemplatePath: service.yaml
    - basename: medium-rc
      objectTemplatePath: rc.yaml
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: RandomizedSaturationTimeLimited
    objectBundle:
    - basename: small-service
      objectTemplatePath: service.yaml
    - basename: small-rc
      objectTemplatePath: rc.yaml
- name: Deleting RCs
- measurements:
  - Identifier: WaitForRunningRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- measurements:
  - Identifier: APIResponsiveness
    Method: APIResponsiveness
    Params:
      action: gather
